In [9]:

import sklearn as sl
import numpy as np
import matplotlib as mp
import pandas as pd
import math
import graphlab

In [3]:
df=graphlab.SFrame('HR_comma_sep.csv')

This non-commercial license of GraphLab Create for academic use is assigned to arunbhat659@gmail.com and will expire on January 10, 2020.

[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\abhat\AppData\Local\Temp\graphlab_server_1547615043.log.0

Finished parsing file C:\Users\abhat\Documents\HR_comma_sep.csv

Parsing completed. Parsed 100 lines in 0.092905 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as
column_type_hints=[float,float,long,long,long,long,long,long,str,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------

Finished parsing file C:\Users\abhat\Documents\HR_comma_sep.csv

Parsing completed. Parsed 14999 lines in 0.051948 secs.

In [11]:
df = pd.read_csv('HR_comma_sep.csv')

In [12]:
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [13]:
df.groupby('left').describe()

            Work_accident  average_montly_hours  last_evaluation  \
left
0    count   11428.000000          11428.000000     11428.000000
     mean        0.175009            199.060203         0.715473
     std         0.379991             45.682731         0.162005
     min         0.000000             96.000000         0.360000
     25%         0.000000            162.000000         0.580000
     50%         0.000000            198.000000         0.710000
     75%         0.000000            238.000000         0.850000
     max         1.000000            287.000000         1.000000
1    count    3571.000000           3571.000000      3571.000000
     mean        0.047326            207.419210         0.718113
     std         0.212364             61.202825         0.197673
     min         0.000000            126.000000         0.450000
     25%         0.000000            146.000000         0.520000
     50%         0.000000            224.000000         0.790000
     75%         0.000000            262.000000         0.900000
     max         1.000000            310.000000         1.000000

            number_project  promotion_last_5years  satisfaction_level  \
left
0    count    11428.000000           11428.000000        11428.000000
     mean         3.786664               0.026251            0.666810
     std          0.979884               0.159889            0.217104
     min          2.000000               0.000000            0.120000
     25%          3.000000               0.000000            0.540000
     50%          4.000000               0.000000            0.690000
     75%          4.000000               0.000000            0.840000
     max          6.000000               1.000000            1.000000
1    count     3571.000000            3571.000000         3571.000000
     mean         3.855503               0.005321            0.440098
     std          1.818165               0.072759            0.263933
     min          2.000000               0.000000            0.090000
     25%          2.000000               0.000000            0.130000
     50%          4.000000               0.000000            0.410000
     75%          6.000000               0.000000            0.730000
     max          7.000000               1.000000            0.920000

            time_spend_company
left
0    count        11428.000000
     mean             3.380032
     std              1.562348
     min              2.000000
     25%              2.000000
     50%              3.000000
     75%              4.000000
     max             10.000000
1    count         3571.000000
     mean             3.876505
     std              0.977698
     min              2.000000
     25%              3.000000
     50%              4.000000
     75%              5.000000
     max              6.000000

In [14]:
df.corr()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
satisfaction_level,1.000000,0.105021,-0.142970,-0.020048,-0.100866,0.058697,-0.388375,0.025605
last_evaluation,0.105021,1.000000,0.349333,0.339742,0.131591,-0.007104,0.006567,-0.008684
number_project,-0.142970,0.349333,1.000000,0.417211,0.196786,-0.004741,0.023787,-0.006064
average_montly_hours,-0.020048,0.339742,0.417211,1.000000,0.127755,-0.010143,0.071287,-0.003544
time_spend_company,-0.100866,0.131591,0.196786,0.127755,1.000000,0.002120,0.144822,0.067433
Work_accident,0.058697,-0.007104,-0.004741,-0.010143,0.002120,1.000000,-0.154622,0.039245
left,-0.388375,0.006567,0.023787,0.071287,0.144822,-0.154622,1.000000,-0.061788
promotion_last_5years,0.025605,-0.008684,-0.006064,-0.003544,0.067433,0.039245,-0.061788,1.000000

In [15]:
sd = pd.get_dummies(df['salary'])
dn = pd.concat([df, sd], axis=1)

In [16]:
dn.drop('salary', axis=1, inplace=True)

In [17]:
dn.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,high,low,medium
0,0.38,0.53,2,157,3,0,1,0,sales,0.0,1.0,0.0
1,0.80,0.86,5,262,6,0,1,0,sales,0.0,0.0,1.0
2,0.11,0.88,7,272,4,0,1,0,sales,0.0,0.0,1.0
3,0.72,0.87,5,223,5,0,1,0,sales,0.0,1.0,0.0
4,0.37,0.52,2,159,3,0,1,0,sales,0.0,1.0,0.0

In [18]:
X = dn.drop(['sales', 'left', 'high'], axis=1)
y = dn['left']

In [19]:
from sklearn.cross_validation import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
m = RandomForestClassifier(n_estimators=100)

In [23]:
m.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [24]:
p = m.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
print(confusion_matrix(y_test, p))
print('\n')
print(classification_report(y_test, p))

[[3760    9]
 [  49 1132]]


             precision    recall  f1-score   support

          0       0.99      1.00      0.99      3769
          1       0.99      0.96      0.98      1181

avg / total       0.99      0.99      0.99      4950

In [27]:
rfc = m.score(X_train, y_train)
print('RFC Train Score:',rfc)
rfctst = m.score(X_test, y_test)
print('RFC Test Score:',rfctst)

('RFC Train Score:', 1.0)
('RFC Test Score:', 0.98828282828282832)

In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
pd.DataFrame(scaler.fit_transform(X_test), columns=X_test.columns)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,low,medium
0,0.615385,0.937500,0.6,0.607477,0.000,1.0,0.0,0.0,1.0
1,0.868132,0.687500,0.2,0.327103,0.000,0.0,0.0,1.0,0.0
2,0.659341,0.968750,0.2,0.551402,0.000,0.0,0.0,1.0,0.0
3,0.351648,0.171875,0.0,0.271028,0.125,0.0,0.0,1.0,0.0
4,0.857143,0.625000,0.6,0.738318,0.000,1.0,0.0,1.0,0.0
5,0.692308,0.812500,0.2,0.598131,0.125,0.0,0.0,1.0,0.0
6,0.978022,0.656250,0.4,0.275701,0.125,1.0,0.0,1.0,0.0
7,0.087912,0.625000,0.4,0.859813,0.375,0.0,0.0,1.0,0.0
8,0.120879,0.968750,0.4,0.327103,0.250,1.0,0.0,0.0,1.0
9,0.076923,0.843750,0.6,0.757009,0.125,0.0,0.0,0.0,1.0
10,0.747253,0.859375,0.6,0.654206,0.375,0.0,0.0,0.0,1.0
11,0.637363,0.546875,0.4,0.294393,0.000,1.0,0.0,0.0,1.0
12,0.494505,0.656250,0.2,0.280374,0.625,0.0,0.0,0.0,1.0
13,0.747253,0.812500,0.0,0.341121,0.125,0.0,0.0,0.0,1.0
14,0.714286,0.984375,0.0,0.845794,0.125,0.0,0.0,0.0,1.0
15,0.549451,0.593750,0.2,0.672897,0.125,0.0,0.0,1.0,0.0
16,0.703297,0.843750,0.2,0.831776,0.000,0.0,0.0,0.0,0.0
17,0.439560,1.000000,0.0,0.135514,0.250,1.0,0.0,1.0,0.0
18,0.912088,0.968750,0.2,0.752336,0.125,0.0,1.0,0.0,1.0
19,0.736264,0.203125,0.6,0.686916,0.125,0.0,0.0,1.0,0.0
20,0.461538,0.437500,0.2,0.799065,0.000,0.0,0.0,1.0,0.0
21,0.373626,0.328125,0.0,0.285047,0.125,0.0,0.0,1.0,0.0
22,0.021978,0.921875,0.8,0.855140,0.250,0.0,0.0,1.0,0.0
23,0.725275,0.875000,0.2,0.481308,0.125,1.0,0.0,1.0,0.0
24,0.395604,0.328125,0.0,0.289720,0.125,0.0,0.0,1.0,0.0
25,0.835165,0.937500,0.4,0.565421,0.375,0.0,0.0,1.0,0.0
26,0.362637,0.187500,0.0,0.219626,0.125,0.0,0.0,1.0,0.0
27,0.604396,0.921875,0.4,0.481308,0.250,0.0,0.0,0.0,1.0
28,0.615385,0.921875,0.0,0.392523,0.000,0.0,0.0,1.0,0.0
29,0.131868,0.015625,0.4,0.154206,0.250,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
4920,0.450549,0.531250,0.6,0.785047,0.000,0.0,0.0,1.0,0.0
4921,0.186813,0.953125,0.2,0.135514,0.000,0.0,0.0,1.0,0.0
4922,0.725275,0.968750,0.2,0.219626,0.000,0.0,0.0,1.0,0.0
4923,0.901099,0.718750,0.0,0.677570,0.125,0.0,0.0,0.0,1.0
4924,0.758242,0.421875,0.6,0.761682,0.125,0.0,0.0,1.0,0.0
4925,0.021978,0.656250,0.8,0.696262,0.250,0.0,0.0,1.0,0.0
4926,0.956044,0.734375,0.4,0.168224,0.500,0.0,0.0,0.0,0.0
4927,0.813187,0.453125,0.2,0.630841,0.000,0.0,0.0,1.0,0.0
4928,0.461538,0.453125,0.4,0.808411,0.125,0.0,0.0,0.0,1.0
4929,0.153846,0.609375,0.8,0.579439,0.125,0.0,0.0,0.0,1.0
4930,0.208791,0.625000,0.2,0.252336,0.000,0.0,0.0,0.0,1.0
4931,0.406593,0.218750,0.0,0.233645,0.125,0.0,0.0,0.0,1.0
4932,0.670330,0.218750,0.2,0.724299,0.000,0.0,0.0,0.0,1.0
4933,0.703297,0.703125,0.2,0.336449,0.000,0.0,0.0,0.0,1.0
4934,0.978022,0.234375,0.2,0.686916,0.000,0.0,0.0,1.0,0.0
4935,0.373626,0.421875,0.2,0.280374,0.125,0.0,0.0,0.0,1.0
4936,0.021978,0.812500,0.8,0.925234,0.250,0.0,0.0,0.0,1.0
4937,0.439560,0.984375,0.8,0.626168,0.250,0.0,0.0,1.0,0.0
4938,0.362637,0.171875,0.0,0.158879,0.125,0.0,0.0,1.0,0.0
4939,0.296703,0.296875,0.0,0.210280,0.125,0.0,0.0,0.0,1.0
4940,0.329670,0.328125,0.0,0.172897,0.125,0.0,0.0,0.0,1.0
4941,0.923077,0.609375,0.6,0.219626,0.125,0.0,0.0,1.0,0.0
4942,0.582418,0.671875,0.2,0.831776,0.125,0.0,0.0,0.0,1.0
4943,0.989011,0.125000,0.8,0.037383,0.500,0.0,0.0,1.0,0.0
4944,0.362637,0.171875,0.0,0.191589,0.125,0.0,0.0,0.0,1.0
4945,0.681319,0.890625,0.2,0.892523,0.375,0.0,0.0,0.0,1.0
4946,0.890110,0.296875,0.4,0.537383,0.125,0.0,0.0,0.0,1.0
4947,0.857143,0.296875,0.4,0.471963,0.125,0.0,0.0,0.0,0.0
4948,0.747253,1.000000,0.4,0.635514,0.375,0.0,0.0,0.0,1.0
4949,0.010989,0.921875,0.8,0.691589,0.375,0.0,0.0,0.0,1.0

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knn = KNeighborsClassifier(n_neighbors=77)

In [51]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=77, p=2,
           weights='uniform')

In [52]:
kp = knn.predict(X_test)

In [53]:
print(confusion_matrix(y_test, kp))

[[3480  289]
 [ 174 1007]]

In [54]:
print(classification_report(y_test, kp))

             precision    recall  f1-score   support

          0       0.95      0.92      0.94      3769
          1       0.78      0.85      0.81      1181

avg / total       0.91      0.91      0.91      4950